# Generated by Django 5.0.7 on 2024-07-17 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Productos',
        ),
    ]
